const loginRoute = '/login/';
const registerRoute = '/register/';
const mainuiRoute = '/mainui/';
const verifyEmailRoute = '/verify-email/';
const newChatRoute = '/chats/new-chat/';
const chatMessageRoute = '/chats/chatmessage/';
const googleSignInRoute = '/google-sign-in/';
const mathematicsChatRoute ='/chats/mathematics/';
const newMathematicsChatRoute ='/chats/mathematics-chat/';